liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        project:
            quality: 45
            filters:
                thumbnail: { size: [900, 400], mode: outbound }

        logo:
            quality: 80
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        icone:
            quality: 80
            filters:
                thumbnail: { size: [48, 48], mode: outbound }